#spring:
#  profiles:
#    active: dev
server:
  port: 9090

# Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  api-docs:
    path: /v3/api-docs

# Ambiente de QA
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://qa-server:3306/db_qa
