server:
  port: 8089

# Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  api-docs:
    path: /v3/api-docs

# Ambiente de Prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://prod-server:3306/db_prod
